In [1]:
import numpy as np
s = np.array([1,2,3,4,5,6,7,8,9])
print(s)
print(type(s))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
y = np.array([1,2,3,4,5,6,7,8,9])
print(y)
print(type(y))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [7]:
#dimention in arry

#0-D:
import numpy as np
x = np.array(4410)
print(x)



4410


In [6]:
#1-D:
import numpy as np
satyam = np.array([4410 , 55 , 22 ,67,398])
print(satyam)


[4410   55   22   67  398]


In [14]:
#2-D:
# Create a 2-D array containig 2 Arrays with certain values.
import numpy as np
satyam = np.array([[4410 , 55 , 22 ,67,398], [1,2,3,4,5]])
print(satyam)


[[4410   55   22   67  398]
 [   1    2    3    4    5]]


In [15]:
# dimention in arry
# Now we will Create a 3-D array with 2-D array.
#3-D:
import numpy as np
x = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])
print(x)



[[[1 2 3 4]
  [4 5 6 7]]

 [[1 2 3 4]
  [4 5 6 7]]]


In [21]:
#Cheack how many dimentions the arry have: ndim attribute
import numpy as np
a = np.array(4410)
b = np.array([4410 , 55 , 22 ,67,398])
c = np.array([[4410 , 55 , 22 ,67,398], [1,2,3,4,5]])
d = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])

print("a number of dimentions : ",a.ndim)
print("b number of dimentions : ",b.ndim)
print("c number of dimentions : ",c.ndim)
print("d number of dimentions : ",d.ndim)

a number of dimentions :  0
b number of dimentions :  1
c number of dimentions :  2
d number of dimentions :  3


In [20]:
# create an array with 5 dimention  and verify it has 5 dimention

import numpy as np
satyam = np.array([1,3,5,7], ndmin=5)
print(satyam)
print("number of dimention: ",satyam.ndim)



[[[[[1 3 5 7]]]]]
number of dimention:  5
