In [9]:
#slicing array -  slicing in python means taking element from one given index to another

#[start:end] , [start:end:step] 

#now we will slice an element an element from 1 to 5 :

import numpy as np
sat = np.array([1,2,3,4,5,6,7,8,9,10])
print(sat[1:5])

# starting to end
print('starting to end :',sat[0:]) 
print("1 to end : ",sat[1:10])

# slicing :[4 to end]
print("4th  to end : ",sat[4:])

# slicing : 0 to 4
print("slicing : 0 to 4 :",sat[:4])


[2 3 4 5]
starting to end : [ 1  2  3  4  5  6  7  8  9 10]
1 to end :  [ 2  3  4  5  6  7  8  9 10]
4th  to end :  [ 5  6  7  8  9 10]
slicing : 0 to 4 : [1 2 3 4]


In [3]:
#
import numpy as np
sat = np.array([1,2,3,4,5,6,7,8,9,10])
print(sat[1:5])

# negative starting to end
print('starting to end : ',sat[:]) 
print('starting to end : ',sat[:-1]) 

#Negative Slicing - index 3 to end
print('index 3 to end : ',sat[-3:-1])

#Negative Slicing - index 5 to 8
print('index 5 to 8 :',sat[-8:-5])


[2 3 4 5]
starting to end :  [ 1  2  3  4  5  6  7  8  9 10]
starting to end :  [1 2 3 4 5 6 7 8 9]
index 3 to end :  [8 9]
index 5 to 8 : [3 4 5]


In [8]:
#
import numpy as np
sat = np.array([1,2,3,4,5,6,7,8,9,10])
print(sat[1:8:2])

print("Even  : ",sat[1::2])
print("Natural : ",sat[::1])
print("odd : ",sat[::2])
print('index 5 to 8 :',sat[-8:-5:-3])


[2 4 6 8]
Even  :  [ 2  4  6  8 10]
Natural :  [ 1  2  3  4  5  6  7  8  9 10]
odd :  [1 3 5 7 9]
index 5 to 8 : []


In [10]:
#2-D slicing :
import numpy as np
satyam = np.array([[4410 , 55 , 22 ,67,398],
                   [1,2,3,4,5]])
print(satyam[1,1:4])

[2 3 4]


In [14]:
#3-D: slicing
import numpy as np
x = np.array([[[1,2,3,4],[4,5,6,7]],
              [[1,2,3,4],[4,5,6,7]]])
print(x[1,1,1:3])  
print(x[0,0,:])
print(x[0,1,1:5])
print(x[: , :])


[5 6]
[1 2 3 4]
[5 6 7]
[[[1 2 3 4]
  [4 5 6 7]]

 [[1 2 3 4]
  [4 5 6 7]]]


In [16]:
#3-D: slicing
import numpy as np
x = np.array([[[1,2,3,4],[4,5,6,7]],
              [[1,2,3,4],[4,5,6,7]]])

print(x[0:3 ,1 :4])


[[[4 5 6 7]]

 [[4 5 6 7]]]
