In [4]:
# Data types in python : String , integer , float , boolean , complex .

# data type in numpy : dtype
# i for integer :
# b for boolean :
# u for unsigned integer :
# f for float :
# c for complex float :
# m  for timedate :
# M for datetime :
# O for object :
# s for string :
# U for unicode string :
# V - memory : 
 
 




int64
<U10


In [9]:
 # Data type to cheking :
 
 #Cheacking the data type of numpy array -dtype
import numpy as np
x = np.array([1,2,3,4,5,6])
print(x.dtype)



int64
string list of fruites data type is :  <U10
[b'1' b'2' b'3' b'4' b'5' b'6']
|S1


In [10]:

#Cheacking the data type of numpy array -string
import numpy as np
xy = np.array(['apple','banana','grephs','cheri','watermelan','orange','peri-peri'])
print("string list of fruites data type is : ",xy.dtype)



string list of fruites data type is :  <U10
[b'1' b'2' b'3' b'4' b'5' b'6']
|S1


In [11]:
# creating array with a defined data type :
import numpy as np
x = np.array([1,2,3,4,5,6],dtype='S')
print(x)
print(x.dtype)



[b'1' b'2' b'3' b'4' b'5' b'6']
|S1


In [18]:

# now we will create an arry with data type of 4 byte int :

import numpy as np
x = np.array([1,2,3,4,5,6],dtype='i4')
print(x)
print(x.dtype)




[1 2 3 4 5 6]
int32


In [30]:
#if a type is given in which the element can't be casted then numpy will raise error. What if a value can't be converted?

import numpy as np
x = np.array(['a','1','b','y','33'],dtype='i')
print(x)
print(x.astype(''))
#print(x.dtype)

ValueError: invalid literal for int() with base 10: 'a'

In [28]:
#Converting data type in existing array - astype()
import numpy as np
x = np.array([1.0, 5.1, .1, 1.2, 1.3])
print(x)
print(x.astype('i'))

[1.  5.1 0.1 1.2 1.3]
[1 5 0 1 1]


In [31]:
#Converting data type from integer to boolean
import numpy as np
x = np.array([1,0,3,8])
print("Given list : ",x)
y = x.astype(bool)
print(y)
print(y.dtype)

Given list :  [1 0 3 8]
[ True False  True  True]
bool


In [32]:
#Converting data type from integer to float
import numpy as np
x = np.array([1,0,3,8])
print("Given list : ",x)
y = x.astype(float)
print(y)
print(y.dtype)

Given list :  [1 0 3 8]
[1. 0. 3. 8.]
float64
