In [1]:
#differance betn numpy array copy and view.
#we will make a copy, change in original arrray, and display both.

import numpy as np

x = np.array([1,3,5,7,9,11,13,15])
y = x.copy()
print(x)
print(y)


[ 1  3  5  7  9 11 13 15]
[ 1  3  5  7  9 11 13 15]


In [4]:
# now we will make a view, change original , display both.

import numpy as np

x = np.array([1,3,5,7,9,11,13,15])
y = x.view()
print(x)
print(y)
x[0]=88
print(x)
print(y)


[ 1  3  5  7  9 11 13 15]
[ 1  3  5  7  9 11 13 15]
[88  3  5  7  9 11 13 15]
[88  3  5  7  9 11 13 15]
