In [2]:
# reshaping - means changing the shape of an array , like adding or removing the elements.

import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

y = x.reshape(4,3)
print(x)
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
# reshaping 1-D to 3-D
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x)
y = x.reshape(2,3,2)  # 2 array , 3 dividing part of array , element of arry
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [10]:
# Return copy or view
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x)
print(x.reshape(2,6).base) # it is a view becosse  of view showes the original documents

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [15]:
# unknown dimention - you are allow to have one unknown demention. pass.

import numpy as np
x = np.array([1,2,3,4,5,6,7,8])
y = x.reshape(2,2,-1)
print(y)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
#flattening the array by converting multidimentional array in 1-D.

import numpy as np 

x = np.array([[1,2,3] ,
              [4,5,6]])

y = x.reshape(-1)
print(x)
print(y)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
# there are alot of funtion for changing the pf an arry in numpy. like flatten , ravel and aldo rearranging the element rot90 , flif , fliplr. they all are actually comes under advanced numpy.



